version: '3.8'

volumes:
  traefik: {}

services:
  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    container_name: traefik
    image: mcardozo/traefik
    networks:
      - proxy
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    volumes:
      - traefik:/etc/traefik/acme:z

networks:
  proxy:
    name: traefik_proxy
