log:
  level: INFO

entryPoints:
  web:
    # http
    address: ":80"

http:
  routers:
    web-router:
      rule: "Host(`localhost`)"
      entryPoints:
        - web
      service: flask

  services:
    flask:
      loadBalancer:
        servers:
          - url: http://flask:5000

providers:
  # https://docs.traefik.io/master/providers/file/
  file:
    filename: /etc/traefik/traefik.yml
    watch: true
