log:
  level: INFO

entryPoints:
  web:
    # http
    address: ":80"

  web-secure:
    # https
    address: ":443"

certificatesResolvers:
  letsencrypt:
    # https://docs.traefik.io/master/https/acme/#lets-encrypt
    acme:
      email: "<your@email.com>"
      storage: /etc/traefik/acme/acme.json
      # https://docs.traefik.io/master/https/acme/#httpchallenge
      httpChallenge:
        entryPoint: web

http:
  routers:
    web-router:
      rule: "Host(`<your-domain.net>`)"
      entryPoints:
        - web
      middlewares:
        - redirect
        - csrf
      service: flask

    web-secure-router:
      rule: "Host(`your-domain.net`)"
      entryPoints:
        - web-secure
      middlewares:
        - csrf
      service: flask
      tls:
        # https://docs.traefik.io/master/routing/routers/#certresolver
        certResolver: letsencrypt

  middlewares:
    redirect:
      # https://docs.traefik.io/master/middlewares/redirectscheme/
      redirectScheme:
        scheme: https
        permanent: true
    csrf:
      # https://docs.traefik.io/master/middlewares/headers/#hostsproxyheaders
      headers:
        hostsProxyHeaders: ["X-CSRFToken"]

  services:
    flask:
      loadBalancer:
        servers:
          - url: http://flask:5000

providers:
  # https://docs.traefik.io/master/providers/file/
  file:
    filename: /etc/traefik/traefik.yml
    watch: true
